services:
  database:
    image: postgres:15.2
    volumes:
      - /database/django_chat:/var/lib/postgresql/data
    ports:
      - "9001:5432"
    container_name: django-chat-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  nginx:
    image: nginx:1.23.3
    container_name: django-chat-nginx
    volumes:
      - ./resources/media:/usr/share/nginx/media
      - ./resources/external:/usr/share/nginx/external
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9002:9002"
      - "9003:9003"
    environment:
      - NGINX_PORT=80
  main:
    build: .
    command: ${DEFAULT_COMMAND}
    container_name: django-chat-app
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
      - STATIC_URL=${STATIC_URL}
      - MEDIA_URL=${MEDIA_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/code
    ports:
      - "9004:9004"
    depends_on:
      - database
      - nginx